<a href="https://colab.research.google.com/github/abdullah1aloush1/AMuGOPIA/blob/main/tensorsMathOperations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [34]:
import torch
import numpy as np

In [35]:
tensorA = torch.tensor([1, 2, 3, 4])
tensorB = torch.tensor([5, 6, 7, 8])

In [36]:
## Addition

tensorA + tensorB

tensor([ 6,  8, 10, 12])

In [37]:
## Addition longhand

torch.add(tensorA, tensorB)

tensor([ 6,  8, 10, 12])

In [38]:
# Subtraction

tensorB - tensorA

tensor([4, 4, 4, 4])

In [39]:
# sub function

torch.sub(tensorB, tensorA)

tensor([4, 4, 4, 4])

In [40]:
## Multiplication

tensorA * tensorB

tensor([ 5, 12, 21, 32])

In [41]:
## Mul longhand

torch.mul(tensorA, tensorB)

tensor([ 5, 12, 21, 32])

In [42]:
## Division

tensorB / tensorA

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [43]:
## Division looghand

torch.div(tensorB, tensorA)

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [44]:
## Remainder Modulus

tensorB % tensorA

tensor([0, 0, 1, 0])

In [45]:
## Remainder longhand

torch.remainder(tensorB, tensorA)

tensor([0, 0, 1, 0])

In [46]:
## Exponents

tensorB ** tensorA

tensor([   5,   36,  343, 4096])

In [47]:
## Exponents longhand

torch.pow(tensorB, tensorA)

tensor([   5,   36,  343, 4096])

In [48]:
## Reassignment

tensorA + tensorB

tensor([ 6,  8, 10, 12])

In [49]:
tensorA.add_(tensorB) ##The underscore reassigns the sum to tensorA
tensorA

tensor([ 6,  8, 10, 12])